#!/usr/bin/env python3
"""
Drives the Husky through the coverage route generated by
generate_coverage_path_grid.py, then returns it to (0, 0, 0).

v4: fixes the "one obstacle aborts the ENTIRE run back to origin" issue.

Previously the whole 81-waypoint route was sent as one giant followPath()
call. followPath() tracks a fixed path with only local costmap nudging --
it can't reroute around something it can't get past, so hitting ANY
obstacle stalled progress until the whole action timed out and FAILED,
which then sent the robot all the way home, abandoning the rest of the
coverage sweep.

v5: followPath calls are now bounded to a short lookahead window
(FOLLOW_PATH_LOOKAHEAD waypoints) instead of the entire remaining route.
v4 built the dense path from waypoints[idx:] -- the WHOLE rest of the
route -- on every retry, which this docstring already claimed was fixed
but wasn't: a run log showed every whole-remaining-route followPath call
stalling with ~0 progress in the full 5s window, succeeding only once
the remaining route shrank to 2 points. Bounding the window keeps each
followPath call small enough for the controller to actually keep up.

Now the route is driven in SHORT SEGMENTS (a few waypoints/lanes at a
time, not the whole route in one call):
  - Each segment is attempted with followPath() first -- straight,
    precise, no smoothing overshoot (as before).
  - If a segment fails/stalls, we fall back to goToPose() for just that
    segment's endpoint -- goToPose DOES invoke Nav2's full global
    planner, which can actually route AROUND an obstacle, unlike
    followPath.
  - Either way, we move on to the next segment afterward instead of
    aborting the whole route. Only genuinely stuck/unreachable segments
    get logged as failed; the robot keeps going and still returns home
    at the very end.

Run this AFTER:
  - simulation.launch.py (world:=office)
  - localization.launch.py (map:=office_map.yaml)
  - nav2_custom.launch.py
  - initialpose has been published
"""

import math
import sys
import time
import yaml
import rclpy
from rclpy.qos import QoSProfile, QoSDurabilityPolicy, QoSHistoryPolicy
from geometry_msgs.msg import PoseStamped
from nav_msgs.msg import Path
from nav2_simple_commander.robot_navigator import BasicNavigator, TaskResult


NAMESPACE = "a200_1103"  # override with --namespace if the serial changes
WAYPOINTS_FILE = "coverage_waypoints_bcd.yaml"
HOME_POSE = (0.0, 0.0, 0.0)  # office_mapEmpty / A200 spawn -- was the
                              # TurtleBot world's (1.303262, 1.481998, pi/2),
                              # carried over. It happened to fall inside the
                              # office room so it never crashed, it just
                              # drove to the wrong place at the end of every
                              # run instead of actually going home.
CONTROLLER_ID = "FollowPath"
ROUTE_VIZ_TOPIC = "planned_coverage_route"

INTERP_STEP_M = 0.15

STALL_TIMEOUT_S = 5.0  # seconds without STALL_EPSILON_M improvement before
                       # declaring a real stall. Previously this was
                       # STALL_TICKS=15 counted loop iterations -- since
                       # isTaskComplete() spins with an internal ~0.1s
                       # timeout per call, 15 ticks was actually only
                       # ~1.7s of real time, confirmed directly from a
                       # run's logs (six separate "stalled" events all
                       # cancelled at ~1.71s, and repeated identical
                       # best_dist_remaining values across them -- the
                       # same stale feedback message being read multiple
                       # times before a fresh one arrived). That's far
                       # too short a grace period for a robot cruising
                       # at ~0.5 m/s over multi-meter segments, and was
                       # cancelling healthy continuous followPath runs
                       # almost immediately, forcing the route into
                       # single-waypoint goToPose hops for nearly its
                       # entire length instead of the intended smooth
                       # continuous drive.
STALL_EPSILON_M = 0.05


def yaw_to_quat(yaw):
    return (0.0, 0.0, math.sin(yaw / 2.0), math.cos(yaw / 2.0))


def make_pose(navigator, x, y, yaw):
    pose = PoseStamped()
    pose.header.frame_id = "map"
    pose.header.stamp = navigator.get_clock().now().to_msg()
    pose.pose.position.x = x
    pose.pose.position.y = y
    qx, qy, qz, qw = yaw_to_quat(yaw)
    pose.pose.orientation.x = qx
    pose.pose.orientation.y = qy
    pose.pose.orientation.z = qz
    pose.pose.orientation.w = qw
    return pose


def build_segment_path(navigator, p0, p1, step_m=INTERP_STEP_M):
    path = Path()
    path.header.frame_id = "map"
    path.header.stamp = navigator.get_clock().now().to_msg()

    x0, y0 = p0["x"], p0["y"]
    x1, y1 = p1["x"], p1["y"]
    dist = math.hypot(x1 - x0, y1 - y0)
    n_steps = max(1, int(dist / step_m))
    yaw = math.atan2(y1 - y0, x1 - x0)

    for s in range(n_steps + 1):
        t = s / n_steps
        x = x0 + (x1 - x0) * t
        y = y0 + (y1 - y0) * t
        path.poses.append(make_pose(navigator, x, y, yaw))

    return path


def run_segment_go_to_pose(navigator, p1):
    goal = make_pose(navigator, p1["x"], p1["y"], p1["yaw"])
    navigator.goToPose(goal)
    while not navigator.isTaskComplete():
        time.sleep(0.05)  # was a bare busy-wait, pinning a core at 100%
                           # for the whole run -- on a machine also running
                           # Gazebo this can itself starve controller_server
                           # of CPU, which is a plausible contributor to the
                           # "missed 20Hz, running at 5.1Hz" warning seen
                           # earlier in this project's logs.
    return navigator.getResult() == TaskResult.SUCCEEDED


def cumulative_distances(waypoints):
    cum = [0.0]
    for i in range(1, len(waypoints)):
        d = math.hypot(waypoints[i]["x"] - waypoints[i - 1]["x"],
                        waypoints[i]["y"] - waypoints[i - 1]["y"])
        cum.append(cum[-1] + d)
    return cum


def build_dense_path(navigator, waypoints, step_m=INTERP_STEP_M):
    path = Path()
    path.header.frame_id = "map"
    path.header.stamp = navigator.get_clock().now().to_msg()
    for i in range(len(waypoints) - 1):
        seg = build_segment_path(navigator, waypoints[i], waypoints[i + 1], step_m)
        poses = seg.poses if i == 0 else seg.poses[1:]
        path.poses.extend(poses)
    if not path.poses:
        path.poses.append(make_pose(navigator, waypoints[-1]["x"],
                                     waypoints[-1]["y"], waypoints[-1]["yaw"]))
    return path


def run_follow_path_stall_aware(navigator, path, stall_timeout_s=STALL_TIMEOUT_S):
    accepted = navigator.followPath(path, controller_id=CONTROLLER_ID)
    if accepted is False:
        return False, None

    best_dist = None
    last_improve_time = time.time()
    while not navigator.isTaskComplete():
        feedback = navigator.getFeedback()
        if feedback:
            d = feedback.distance_to_goal
            if best_dist is None or d < best_dist - STALL_EPSILON_M:
                best_dist = d
                last_improve_time = time.time()
            elif time.time() - last_improve_time > stall_timeout_s:
                print(f"    stalled ({stall_timeout_s:.1f}s without "
                      f"{STALL_EPSILON_M}m of progress) -- cancelling and replanning around it")
                navigator.cancelTask()
                return False, best_dist

    ok = navigator.getResult() == TaskResult.SUCCEEDED
    return ok, (0.0 if ok else best_dist)


def main():
    rclpy.init(args=sys.argv)

    # --namespace overrides NAMESPACE -- e.g. `--namespace a200_2201` if the
    # robot's serial changes. Parsed before BasicNavigator is constructed
    # since the namespace has to be known at that point.
    namespace = NAMESPACE
    if "--namespace" in sys.argv:
        namespace = sys.argv[sys.argv.index("--namespace") + 1]
    print(f"Namespace: {namespace}")

    navigator = BasicNavigator(namespace=namespace)
    navigator.set_parameters([
        rclpy.parameter.Parameter('use_sim_time', rclpy.Parameter.Type.BOOL, True)
    ])
    navigator.waitUntilNav2Active()

    # Optional settling pause before the first goal -- waitUntilNav2Active()
    # confirms lifecycle nodes are up, not that the local costmap has
    # finished populating from a just-published AMCL pose. Matches the
    # "instant ABORT / costmap not ready" pattern already documented in
    # Phase 5 (run 1785231394, and Progress Update v2's Run 2). Test with
    # e.g. `--settle 5`; if early-waypoint stalls disappear, that confirms
    # the root cause cheaply before assuming a routing/algorithm defect.
    if "--settle" in sys.argv:
        settle_s = float(sys.argv[sys.argv.index("--settle") + 1])
        print(f"Settling {settle_s}s before first goal...")
        time.sleep(settle_s)

    # --stall-timeout overrides STALL_TIMEOUT_S -- e.g. `--stall-timeout 8`
    # if 5s default still cancels healthy runs, or `--stall-timeout 2` to
    # confirm the OLD ~1.7s behavior was in fact the false-stall cause.
    stall_timeout_s = STALL_TIMEOUT_S
    if "--stall-timeout" in sys.argv:
        stall_timeout_s = float(sys.argv[sys.argv.index("--stall-timeout") + 1])
    print(f"Stall timeout: {stall_timeout_s}s")

    # --waypoints overrides WAYPOINTS_FILE without hand-editing the source --
    # e.g. `python3 run_coverage.py --waypoints coverage_waypoints_bsa.yaml`.
    # Default stays coverage_waypoints.yaml so existing invocations behave
    # exactly as before.
    waypoints_file = WAYPOINTS_FILE
    if "--waypoints" in sys.argv:
        waypoints_file = sys.argv[sys.argv.index("--waypoints") + 1]
    print(f"Loading route from: {waypoints_file}")

    with open(waypoints_file, "r") as f:
        data = yaml.safe_load(f)
    waypoints = data["waypoints"]
    cum = cumulative_distances(waypoints)

    full_path = Path()
    full_path.header.frame_id = "map"
    full_path.header.stamp = navigator.get_clock().now().to_msg()
    for wp in waypoints:
        full_path.poses.append(make_pose(navigator, wp["x"], wp["y"], wp["yaw"]))
    qos = QoSProfile(depth=1, durability=QoSDurabilityPolicy.TRANSIENT_LOCAL,
                      history=QoSHistoryPolicy.KEEP_LAST)
    route_pub = navigator.create_publisher(Path, ROUTE_VIZ_TOPIC, qos)
    route_pub.publish(full_path)
    print(f"Published planned route to '/{namespace}/{ROUTE_VIZ_TOPIC}' for RViz.")

    MAX_HOPS = 3
    # v5: followPath was being handed the ENTIRE remaining route on every
    # retry (waypoints[idx:], not "one segment"), despite the docstring
    # above literally claiming segment-at-a-time driving. Confirmed via
    # run log: every single whole-remaining-route followPath call stalled
    # near-instantly with ~0 progress in the full 5s window (matching
    # control_server's own "missed 20Hz, running at 5.1Hz" warning from a
    # prior run), except the final call once only 2 points were left. A
    # bounded lookahead window keeps each followPath call cheap enough for
    # MPPI to actually make progress, while still getting multi-lane
    # smooth driving instead of falling back to single-waypoint goToPose
    # hops for the entire route.
    # v6: LOOKAHEAD dropped from 4 to 1. With 4, every window bundled one easy
    # long ~11m straight cruise together with the plan's genuinely hardest
    # maneuver -- a ~0.55m sideways hop requiring a full stop + sharp reversal
    # right after the cruise built up speed. Every run this project has done,
    # regardless of AMCL tuning or costmap settings, failed at exactly the
    # same waypoints -- the ones sitting at that hop, always 1-2 waypoints
    # after a window boundary. That consistency across otherwise-unrelated
    # config changes is the signal that this was never a localization or
    # costmap problem: it's followPath getting a cold-started MPPI optimizer
    # and immediately demanding its hardest turn of the whole route. At
    # LOOKAHEAD=1, each followPath call is exactly one segment -- easy
    # straight segments stay smooth and precise via followPath; a hard
    # reversal segment fails fast on its own and falls straight to goToPose's
    # full global planner, which has reached every one of these points within
    # 1-3 tries in every log we have. Costs a little continuous-driving
    # smoothness; buys reliability on the segments that actually need it.
    FOLLOW_PATH_LOOKAHEAD = 1
    failed_waypoints = []
    idx = 0
    n_waypoints = len(waypoints)

    while idx < n_waypoints - 1:
        window_end = min(idx + FOLLOW_PATH_LOOKAHEAD, n_waypoints - 1)
        remaining = waypoints[idx:window_end + 1]
        print(f"Driving continuous path: waypoint {idx} -> {window_end} "
              f"({len(remaining)} waypoints, one smooth followPath call)")
        path = build_dense_path(navigator, remaining)
        ok, best_dist_remaining = run_follow_path_stall_aware(navigator, path, stall_timeout_s)

        if ok:
            print(f"Segment {idx}->{window_end} complete.")
            idx = window_end
            continue

        seg_total = cum[window_end] - cum[idx]
        print(f"    [diagnostic] stalled during {idx}->{window_end}: "
              f"seg_total={seg_total:.2f}m, best_dist_remaining="
              f"{best_dist_remaining if best_dist_remaining is not None else 'None'}"
              f"{'m' if best_dist_remaining is not None else ''} "
              f"(if this is much smaller than seg_total, that's the old bug)")
        target = min(idx + 1, n_waypoints - 1)

        hop_idx = target
        hopped = False
        skipped_hops = []
        for _ in range(MAX_HOPS):
            if hop_idx >= n_waypoints:
                break
            print(f"    replanning (goToPose) to waypoint {hop_idx} to clear the obstruction...")
            if run_segment_go_to_pose(navigator, waypoints[hop_idx]):
                hopped = True
                break
            skipped_hops.append(hop_idx)
            hop_idx += 1

        if hopped:
            if skipped_hops:
                print(f"    waypoint(s) {skipped_hops} silently skipped during hop "
                      f"retry -- recovery succeeded at {hop_idx} instead "
                      f"(Issue 6b: previously these were never recorded)")
                failed_waypoints.extend(skipped_hops)
            idx = hop_idx
        else:
            print(f"    could not recover near waypoint {target} -- skipping ahead")
            failed_waypoints.append(target)
            idx = max(idx + 1, target)

    print(f"\nRoute finished. {len(failed_waypoints)} waypoint(s) could not "
          f"be reached even with replanning fallback.")
    if failed_waypoints:
        print(f"Unreached waypoint indices: {failed_waypoints}")

    print("Returning home...")
    home = make_pose(navigator, *HOME_POSE)
    navigator.goToPose(home)
    while not navigator.isTaskComplete():
        time.sleep(0.05)  # see note in run_segment_go_to_pose()

    if navigator.getResult() == TaskResult.SUCCEEDED:
        print(f"Back at {HOME_POSE[:2]}. Done.")
    else:
        print("Failed to return home -- check Nav2 / costmap state.")

    rclpy.shutdown()


if __name__ == "__main__":
    main()
